name: with cache
"on":
  push:
    branches:
      - main
jobs:
  build_sdks:
    name: Run Pulumi with NPM Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Install and run Pulumi CLI
        uses: pulumi/actions@v5
        with:
            cloud-url: file://~
            command: up
            upsert: true
            stack-name: withcache
      